### ISSUE TITLE
Error getting random quotes: Unable to parse response from API

### ISSUE THREAD

**Issue by s0ul3vans** [dotzenith/AvatarSay#1]
I think AvatarAPI.rs doesnt work. error returned from database: (code: 1) no such table: quotes

**Comment by dotzenith** [comment]
I unfortunately broke AvatarAPI.rs for a little bit because of an update, I pushed a hotfix for now and it should work just fine. Please let me know if it breaks again, I'll keep an eye out for the next couple of days and merge the hotfix if it doesn't break again.

Here is the actual problem: https://github.com/launchbadge/sqlx/issues/1647#issuecomment-1020677837

**Comment by s0ul3vans** [comment]
Everything is working now. Thanks!
![2024-12-04-234627_hyprshot](https://github.com/user-attachments/assets/ff7ebf67-3dc5-40b4-8f12-12876514d5b6)
